#ifndef DRAWITEMTYPE_H
#define DRAWITEMTYPE_H


enum DrawItemType
{
    SHAPE_CIRCLE,
    SHAPE_DIAMOND,
    SHAPE_LINE,
    SHAPE_OVAL,
    SHAPE_PARALLELOGRAM,
    SHAPE_RECTANGLE,
    SHAPE_TRIANGLE,
    DATE_TIME_ITEM,
    DATE_ITEM,
    TIME_ITEM,
    TEXT_ITEM,
    IMAGE_ITEM,
    BARCODE_ITEM,
    COUNTER_ITEM
};

#endif // DRAWITEMTYPE_H
