#ifndef MOUSEMOVERESULT_H
#define MOUSEMOVERESULT_H


enum MouseMoveResult
{
    NOTHING = 0 ,
    INSIDE = 1,
    IN_DRAGING_MODE = 2,
    TOP_RESIZE = 3,
    LEFT_RESIZE = 4,
    RIGHT_RESIZE = 5,
    BOTTOM_RESIZE = 6,
    LEFT_TOP_RESIZE = 7,
    LEFT_BOTTOM_RESIZE = 8,
    RIGHT_TOP_RESIZE = 9 ,
    RIGHT_BOTTOM_RESIZE =10,
    TOP_RESIZE_PRESSED = 11,
    LEFT_RESIZE_PRESSED = 12,
    RIGHT_RESIZE_PRESSED = 13,
    BOTTOM_RESIZE_PRESSED = 14,
    LEFT_TOP_RESIZE_PRESSED = 15,
    LEFT_BOTTOM_RESIZE_PRESSED = 16,
    RIGHT_TOP_RESIZE_PRESSED = 17 ,
    RIGHT_BOTTOM_RESIZE_PRESSED =18,
    ROTATE =19

};

#endif // MOUSEMOVERESULT_H
